title: Flytipping incidents and actions reported by local authorities in 2010-11
description: A dataset taken from <a href="http://data.gov.uk/dataset/fly-tipping_in_england" target="_blank">data.gov.uk</a> used here to demonstrate the open data publishing template in Github. This dataset is a monthly-updated list of all financial transactions spending over £25,000 made by the Foreign and Commonwealth Office, as part of the Government's commitment to transparency in expenditure.

publisher_text: Department for Environment, Food and Rural Affairs
publisher_url: https://www.gov.uk/government/organisations/department-for-environment-food-rural-affairs

license_text: UK Open Government Licence (OGL)
license_url: http://reference.data.gov.uk/id/open-government-licence

frequency: Infrequent

certificate_embed: 
